### ISSUE TITLE
Installation v2

### ISSUE THREAD

**Issue by KoenWindey** [coussej/node-opcua-logger#23]
Hi Jeroen,

I've been trying to install the logger v2 on Ubuntu 18.0.4. 

Using `npm install` throws errors: `Error: EACCES: permission denied, mkdir '/home/koen/node-opcua-logger-2/node_modules/node-opcua-certificate-manager/certificates'`

Even a `sudo npm install` doesn't solve this.

I then tried `sudo npm install --unsafe-perm=true --allow-root` and that seemed to install ok. However, as soon as I ran 'node logger.js' I got an error: Error: Cannot find module 'nedb'. I resolved this by running  `sudo npm install nedb --save`.

Next issue, again as soon as I run 'node logger.js', I get the following error

```
/home/koen/node-opcua-logger-2/writepump.js:18
	this.output = new influx({
	              ^

TypeError: influx is not a constructor
    at new WritePump (/home/koen/node-opcua-logger-2/writepump.js:18:16)
    at Object.<anonymous> (/home/koen/node-opcua-logger-2/logger.js:11:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I then changed line 18 in writepump.js to `this.output = new influx.InfluxDB({` and that made the issue go away. Perhaps the syntax for influx changed ?

Then, again when executing `node logger.js`, I get the following error:

```
/home/koen/node-opcua-logger-2/readpump.js:20
    self.uaClient.connect(self.uaServerUrl, function(err) {
                  ^

TypeError: self.uaClient.connect is not a function
    at ReadPump.ConnectOPCUA (/home/koen/node-opcua-logger-2/readpump.js:20:19)
    at /home/koen/node-opcua-logger-2/readpump.js:319:22
    at nextTask (/home/koen/node-opcua-logger-2/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/home/koen/node-opcua-logger-2/node_modules/async/dist/async.js:5334:5)
    at ReadPump.Run (/home/koen/node-opcua-logger-2/readpump.js:316:11)
    at /home/koen/node-opcua-logger-2/logger.js:19:6
    at /home/koen/node-opcua-logger-2/node_modules/async/dist/async.js:3269:12
    at /home/koen/node-opcua-logger-2/node_modules/async/dist/async.js:74:12
    at next (/home/koen/node-opcua-logger-2/node_modules/async/dist/async.js:3514:9)
    at Object.forever (/home/koen/node-opcua-logger-2/node_modules/async/dist/async.js:3516:5)
```

This time I gave up. :-/ ... something seems fishy - surely something went wrong with my original install? I shouldn't have to chase errors like this to make it work, right? Or.... Could it have anything to do with this [issue, commented on by E Rossignon late 2018 ? ](https://github.com/node-opcua/node-opcua/issues/574#issuecomment-448792798)

Any suggestions?  

Koen

**Comment by coussej** [comment]
Hi Koen, 

yeah sorry, the v2 branch is stil heavily WIP. You should run `node ./src/index.js` instead of `node logger.js`. I still need to cleanup some files from the old version, planning on releasing an alpha later this week.

**Comment by coussej** [comment]
Hello Koen, 
v2 is now merged in master, and includes better documentation in the readme. 

Could you either try again from source, or download a binary from the release page? Let me know if it works!
