### ISSUE TITLE
Error: cannot find version block

### ISSUE THREAD

**Issue by WildEgor** [coussej/node-opcua-logger#65]
[2021-04-16T15:05:34.768] [FATAL] main - Error: cannot find version block
    at Object.start (F:\Common\Programming\Playground\node-opcua-logger-2.0.0-alpha\src\opcua.js:62:11)
    at async F:\Common\Programming\Playground\node-opcua-logger-2.0.0-alpha\src\index.js:50:5

Hello, what's wrong here?

**Comment by coussej** [comment]
Did you re-execute npm install after switching branches?
